project:
    type: website
    output-dir: docs
website:
    navbar:
        title: "pickpj"
        tools:
          - icon: github
            href: https://www.github.com/pickpj
    sidebar:
        style: "docked"
        contents:
          - section: "Mapping"
            contents:
            - section: "Custom Routing"
              contents:
              - href: Mapping/custom-routing-maps/comaps.qmd
                text: Comaps
              - href: Mapping/custom-routing-maps/osmand.qmd
                text: Osmand
            - section: "FIock"
              contents:
              - href: Mapping/FIock/bigbrouter.qmd
                text: Big B-router
              - href: Mapping/FIock/bridges.qmd
                text: Bridges
              - href: Mapping/FIock/diff.qmd
                text: BC - No Road Overlap
              - href: Mapping/FIock/directionless.qmd
                text: BC - No Direction Tag
              - href: Mapping/FIock/similar.qmd
                text: BC - Similar ALPRs
              - href: Mapping/FIock/binghamton.qmd
                text: BC - Binghamton, NY
            - section: "Working w/ big maps"
              contents:
              - href: Mapping/big-pbf/pbf-splitter.qmd
                text: Splitting a big pbf (wrong)
              - href: Mapping/big-pbf/tags-filter.qmd
                text: Tags-filtering a large pbf
            - section: "Japan"
              contents:
              - href: Mapping/JPN/tokyochizu.qmd
                text: Various maps
          - section: "ML/DL"
            contents:
              - section: "Image"
                contents:
                - href: MLDL/fastai.qmd
                  text: Image Classification
          - section: "Linux"
            contents:
              - section: "Keyboard"
                contents:
                - href: Linux/keyboard/evmorse.qmd
                  text: ev-morse 
                - href: Linux/keyboard/keycodes.qmd
                  text: keycode list
              - href: Linux/x11/macro-migration.qmd
                text: x11->wayland macros
          # - section: "Other"
          #   contents:
          #   - href: Other/reusing.qmd
          #     text: ♻️ Reusing Electronics
format:
    html:
        title-prefix: pickpj
        lightbox: true
        theme: morph-dark.scss
        toc: true