project:
    type: website
    output-dir: docs
website:
    navbar:
        title: "pickpj"
        tools:
          - icon: github
            href: https://www.github.com/pickpj
    sidebar:
        style: "docked"
        contents:
          - section: "ML/DL"
            contents:
              - section: "Image"
                contents:
                  - href: MLDL/fastai.qmd
                    text: Image Classification
                  - href: MLDL/imtools.qmd
                    text: Tools
              - section: "Tabular"
                contents:
                  - href: MLDL/tabtools.qmd
                    text: Tools
          - section: "Keyboard"
            contents:
              - href: evmorse.qmd
                text: ev-morse 
              - href: keycodes.qmd
                text: keycode list
          - section: "Other"
            contents:
              - href: reusing.qmd
                text: ♻️ Reusing Electronics
format:
    html:
        theme: superhero
        toc: true